fix rubocop config
There are some rubocop complaints about the outdated config:
```
.rubocop-disables.yml: Metrics/LineLength has the wrong namespace - should be Layout
222Error: The `Layout/IndentFirstHashElement` cop has been renamed to `Layout/FirstHashElementIndentation`.
223(obsolete configuration found in .rubocop-disables.yml, please update it)
224The `Lint/HandleExceptions` cop has been renamed to `Lint/SuppressedException`.
225(obsolete configuration found in .rubocop-disables.yml, please update it)
226The `Lint/StringConversionInInterpolation` cop has been renamed to `Lint/RedundantStringCoercion`.
227(obsolete configuration found in .rubocop-disables.yml, please update it)
228The `Style/UnneededPercentQ` cop has been renamed to `Style/RedundantPercentQ`.
229(obsolete configuration found in .rubocop-disables.yml, please update it)
230The `Style/BracesAroundHashParameters` cop has been removed.
231(obsolete configuration found in .rubocop-disables.yml, please update it)
232RuboCop failed!
```

This PR fixes it.