Fix typo on AbstractResponse#return!
This was causing the following error on unknown status codes:

  undefined method `RequestFailed' for #<String:0x00000102bf1a50> (NoMethodError)